### ISSUE TITLE
Rename appExtension.dll

### ISSUE THREAD

**Issue by AlenToma** [Rustemsoft/Skater-.NET-Obfuscator#2]
Im using Command line to obfuscator my project and this create `appExtension.dll` when using `-c`

Is it possible to choose another name for this dll by commandline, Or is it possible to reanme it without any problem ?

After i obfuscator more then one project, there will exist more then one `appExtension.dll` and this will create a problem for me when i create an `.apk`

**Comment by Rustemsoft** [comment]
Hello Alen Toma*,*
The Separate DLL file name is not hard-coded in Skater. You may enter any
name of the DLL to name the appExtensions differently for each obfuscated
exe.
[image: image.png]
Please read Skater on-line documentation:
http://rustemsoft.com/SkaterDoc/index.html
'String encryption' topic.

Thank you,

Support Team
*Rustemsoft LLC*

**Comment by AlenToma** [comment]
I know that, but its only by GUI or the creation of setting.xml. I wanted a command line solution.

I have build a usertask that should work with all project

```
  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(Configuration)'=='Release'">
    <Obfuscation StayOpen="false" ApplicationPath="C:\Program Files (x86)\RustemSoft\Skater\Skater.exe" Source="$(TargetPath)" Hidden="true" ShowString="true" />
  </Target>
```

I did not want to have an xml setting for each project.

If its not possiable then i could build an xaml setting that could work for all project :)

Here is another problem that i encounter.

When i choose `ShowString= false` then the `appExtension.dll` will be created, but sadly when i create or archive an apk this dll dose not get included in the assembly map, inside the apk which create a big problem.

I dont know if its possiable but must this dll gets created ? is it not possiable to simple hide those string or simple encrypt them without the extra dll gets created? 

Im using the professtional build so all settings are included

**Comment by AlenToma** [comment]
well i got it, with `-f` all `strings` are hidden :) so no need to use `-c` anymore.
